//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLPRibbonTab.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PulldownButtonDatas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PulldownButtonDatas() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLPRibbonTab.Resources.PulldownButtonDatas", typeof(PulldownButtonDatas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string FamilyUtils_DescriptionLong {
            get {
                return ResourceManager.GetString("FamilyUtils_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набор утилит для работы с семействами.
        /// </summary>
        internal static string FamilyUtils_DescriptionShort {
            get {
                return ResourceManager.GetString("FamilyUtils_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утилиты 
        ///для семейств.
        /// </summary>
        internal static string FamilyUtils_Name {
            get {
                return ResourceManager.GetString("FamilyUtils_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string ModellingConnections_DescriptionLong {
            get {
                return ResourceManager.GetString("ModellingConnections_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты для работы с отверстиями.
        /// </summary>
        internal static string ModellingConnections_DescriptionShort {
            get {
                return ResourceManager.GetString("ModellingConnections_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения.
        /// </summary>
        internal static string ModellingConnections_Name {
            get {
                return ResourceManager.GetString("ModellingConnections_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string ModellingVoids_DescriptionLong {
            get {
                return ResourceManager.GetString("ModellingVoids_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструменты для работы с отверстиями.
        /// </summary>
        internal static string ModellingVoids_DescriptionShort {
            get {
                return ResourceManager.GetString("ModellingVoids_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отверстия.
        /// </summary>
        internal static string ModellingVoids_Name {
            get {
                return ResourceManager.GetString("ModellingVoids_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string ParametersAuto_DescriptionLong {
            get {
                return ResourceManager.GetString("ParametersAuto_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функции &quot;автопараметров&quot; ГК Олимпроект.
        /// </summary>
        internal static string ParametersAuto_DescriptionShort {
            get {
                return ResourceManager.GetString("ParametersAuto_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автопараметры.
        /// </summary>
        internal static string ParametersAuto_Name {
            get {
                return ResourceManager.GetString("ParametersAuto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string ParametersFill_DescriptionLong {
            get {
                return ResourceManager.GetString("ParametersFill_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набор инструментов для заполнения параметров.
        /// </summary>
        internal static string ParametersFill_DescriptionShort {
            get {
                return ResourceManager.GetString("ParametersFill_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполнить.
        /// </summary>
        internal static string ParametersFill_Name {
            get {
                return ResourceManager.GetString("ParametersFill_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string SchedulesUtils_DescriptionLong {
            get {
                return ResourceManager.GetString("SchedulesUtils_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набор утилит для работы со спецификациями.
        /// </summary>
        internal static string SchedulesUtils_DescriptionShort {
            get {
                return ResourceManager.GetString("SchedulesUtils_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спец-ии.
        /// </summary>
        internal static string SchedulesUtils_Name {
            get {
                return ResourceManager.GetString("SchedulesUtils_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string SheetsUtils_DescriptionLong {
            get {
                return ResourceManager.GetString("SheetsUtils_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набор утилит для работы с листами.
        /// </summary>
        internal static string SheetsUtils_DescriptionShort {
            get {
                return ResourceManager.GetString("SheetsUtils_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Листы.
        /// </summary>
        internal static string SheetsUtils_Name {
            get {
                return ResourceManager.GetString("SheetsUtils_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string ViewsUtils_DescriptionLong {
            get {
                return ResourceManager.GetString("ViewsUtils_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набор утилит для работы с видами (кроме спецификаций).
        /// </summary>
        internal static string ViewsUtils_DescriptionShort {
            get {
                return ResourceManager.GetString("ViewsUtils_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виды.
        /// </summary>
        internal static string ViewsUtils_Name {
            get {
                return ResourceManager.GetString("ViewsUtils_Name", resourceCulture);
            }
        }
    }
}
