//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLPRibbonTab.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PushButtonDatas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PushButtonDatas() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLPRibbonTab.Resources.PushButtonDatas", typeof(PushButtonDatas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коллизии.
        /// </summary>
        internal static string CheckCollisions_Name {
            get {
                return ResourceManager.GetString("CheckCollisions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model
        ///Checker.
        /// </summary>
        internal static string CheckModel_Name {
            get {
                return ResourceManager.GetString("CheckModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры.
        /// </summary>
        internal static string CheckParameters_Name {
            get {
                return ResourceManager.GetString("CheckParameters_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать.
        /// </summary>
        internal static string ExportPrint_Name {
            get {
                return ResourceManager.GetString("ExportPrint_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт Excel.
        /// </summary>
        internal static string ExportXLS_Name {
            get {
                return ResourceManager.GetString("ExportXLS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт
        ///DWG.
        /// </summary>
        internal static string ImportDWG_Name {
            get {
                return ResourceManager.GetString("ImportDWG_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связи
        ///RVT/DWG.
        /// </summary>
        internal static string ImportLinks_Name {
            get {
                return ResourceManager.GetString("ImportLinks_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Браузер видов.
        /// </summary>
        internal static string ManageBrowseViews {
            get {
                return ResourceManager.GetString("ManageBrowseViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Family
        ///Manager.
        /// </summary>
        internal static string ManageFamilies_Name {
            get {
                return ResourceManager.GetString("ManageFamilies_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материалы.
        /// </summary>
        internal static string ManageMaterials_Name {
            get {
                return ResourceManager.GetString("ManageMaterials_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task v1.
        /// </summary>
        internal static string ManageTask1_Name {
            get {
                return ResourceManager.GetString("ManageTask1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task v2.
        /// </summary>
        internal static string ManageTask2_Name {
            get {
                return ResourceManager.GetString("ManageTask2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединить элементы.
        /// </summary>
        internal static string ModellingAutoJoin_Name {
            get {
                return ResourceManager.GetString("ModellingAutoJoin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединения стен/балок.
        /// </summary>
        internal static string ModellingConnectWallBeam_Name {
            get {
                return ResourceManager.GetString("ModellingConnectWallBeam_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прорезать полости.
        /// </summary>
        internal static string ModellingCutByVoids_Name {
            get {
                return ResourceManager.GetString("ModellingCutByVoids_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отверстия
        ///в кладке.
        /// </summary>
        internal static string ModellingMasonaryOpenings_Name {
            get {
                return ResourceManager.GetString("ModellingMasonaryOpenings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фоновый режим.
        /// </summary>
        internal static string ParametersAutoOLPAuto_Name {
            get {
                return ResourceManager.GetString("ParametersAutoOLPAuto_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ручной режим.
        /// </summary>
        internal static string ParametersAutoOLPManual_Name {
            get {
                return ResourceManager.GetString("ParametersAutoOLPManual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать параметры.
        /// </summary>
        internal static string ParametersCopier_Name {
            get {
                return ResourceManager.GetString("ParametersCopier_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры заказчика.
        /// </summary>
        internal static string ParametersCustomer_Name {
            get {
                return ResourceManager.GetString("ParametersCustomer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры отметок.
        /// </summary>
        internal static string ParametersElevation_Name {
            get {
                return ResourceManager.GetString("ParametersElevation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработка типов, параметров.
        /// </summary>
        internal static string ParametersFamily_Name {
            get {
                return ResourceManager.GetString("ParametersFamily_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр &quot;Номер секции&quot;.
        /// </summary>
        internal static string ParametersNSection_Name {
            get {
                return ResourceManager.GetString("ParametersNSection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настроить ширину столбца.
        /// </summary>
        internal static string SchedulesColumnWidth_Name {
            get {
                return ResourceManager.GetString("SchedulesColumnWidth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заменить фильтр.
        /// </summary>
        internal static string SchedulesFilterReplacer_Name {
            get {
                return ResourceManager.GetString("SchedulesFilterReplacer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить ИЗМ.
        /// </summary>
        internal static string SheetsAddRevision_Name {
            get {
                return ResourceManager.GetString("SheetsAddRevision_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать листы.
        /// </summary>
        internal static string SheetsCopier_Name {
            get {
                return ResourceManager.GetString("SheetsCopier_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нумератор листов.
        /// </summary>
        internal static string SheetsEnumerator_Name {
            get {
                return ResourceManager.GetString("SheetsEnumerator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать в буфер видов.
        /// </summary>
        internal static string ViewsCopy_Name {
            get {
                return ResourceManager.GetString("ViewsCopy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать виды.
        /// </summary>
        internal static string ViewsCreator_Name {
            get {
                return ResourceManager.GetString("ViewsCreator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить разрез на лист.
        /// </summary>
        internal static string ViewsInsertSectionViewport_Name {
            get {
                return ResourceManager.GetString("ViewsInsertSectionViewport_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать виды.
        /// </summary>
        internal static string ViewsMultiCopier_Name {
            get {
                return ResourceManager.GetString("ViewsMultiCopier_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставить из буфера видов.
        /// </summary>
        internal static string ViewsPaste_Name {
            get {
                return ResourceManager.GetString("ViewsPaste_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переименовать виды.
        /// </summary>
        internal static string ViewsRenamer_Name {
            get {
                return ResourceManager.GetString("ViewsRenamer_Name", resourceCulture);
            }
        }
    }
}
