//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLPRibbonTab.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToggleButtonDatas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToggleButtonDatas() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLPRibbonTab.Resources.ToggleButtonDatas", typeof(ToggleButtonDatas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string WorkMode_All_DescriptionLong {
            get {
                return ResourceManager.GetString("WorkMode_All_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает все плагины.
        /// </summary>
        internal static string WorkMode_All_DescriptionShort {
            get {
                return ResourceManager.GetString("WorkMode_All_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим &quot;Все&quot;.
        /// </summary>
        internal static string WorkMode_All_Name {
            get {
                return ResourceManager.GetString("WorkMode_All_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string WorkMode_OAP_DescriptionLong {
            get {
                return ResourceManager.GetString("WorkMode_OAP_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает плагины только для отдела &quot;ОАП&quot;.
        /// </summary>
        internal static string WorkMode_OAP_DescriptionShort {
            get {
                return ResourceManager.GetString("WorkMode_OAP_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим &quot;ОАП&quot;.
        /// </summary>
        internal static string WorkMode_OAP_Name {
            get {
                return ResourceManager.GetString("WorkMode_OAP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string WorkMode_OIS_DescriptionLong {
            get {
                return ResourceManager.GetString("WorkMode_OIS_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает плагины только для отдела &quot;ОИС&quot;.
        /// </summary>
        internal static string WorkMode_OIS_DescriptionShort {
            get {
                return ResourceManager.GetString("WorkMode_OIS_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим &quot;ОИС&quot;.
        /// </summary>
        internal static string WorkMode_OIS_Name {
            get {
                return ResourceManager.GetString("WorkMode_OIS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string WorkMode_OSK_DescriptionLong {
            get {
                return ResourceManager.GetString("WorkMode_OSK_DescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает плагины только для отдела &quot;ОСК&quot;.
        /// </summary>
        internal static string WorkMode_OSK_DescriptionShort {
            get {
                return ResourceManager.GetString("WorkMode_OSK_DescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим &quot;ОСК&quot;.
        /// </summary>
        internal static string WorkMode_OSK_Name {
            get {
                return ResourceManager.GetString("WorkMode_OSK_Name", resourceCulture);
            }
        }
    }
}
